#!/usr/bin/env ruby

$VERBOSE = nil

require "jekyll"

Jekyll.logger.adjust_verbosity(
  :quiet => true
)

Jekyll::PluginManager.require_from_bundler

config = Jekyll.configuration
config["future"] = true

site = Jekyll::Site.new(config)
site.reset
site.read

staged_files = `git diff --cached --name-only --diff-filter=ACM`.split("\n")
staged_posts = Array.new

site.posts.docs.each do |p|
  if (staged_files.include? p.path.gsub(Dir.pwd + "/", ""))
    staged_posts.push(p)
  end
end

puts staged_posts.length

site.config["pre-commit"].each do |c|
  i = Object.const_get("Jekyll::PreCommit::Check::" + c).new
  puts i.Check
end
