#!/usr/bin/env ruby

$VERBOSE = nil

require "jekyll"

Jekyll.logger.adjust_verbosity(
  :quiet => true
)

Jekyll::PluginManager.require_from_bundler

config = Jekyll.configuration
config["future"] = true

site = Jekyll::Site.new(config)
site.reset
site.read

staged_files = `git diff --cached --name-only --diff-filter=ACM`.split("\n")

runner = Jekyll::PreCommit::Runner.new
messages = runner.run(site, staged_files)

if messages.empty?
  exit(0)
end

puts "There were failed checks 😥"
messages.each do |c|
  puts c
end
exit(1)
